namespace GUI.DanhMuc
{
    partial class f_giamgia
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f_giamgia));
            this.dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.Root = new DevExpress.XtraLayout.LayoutControlGroup();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.phantramSpinEdit = new DevExpress.XtraEditors.SpinEdit();
            this.ItemForphantram = new DevExpress.XtraLayout.LayoutControlItem();
            this.giamgiaBindingSource = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).BeginInit();
            this.dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Root)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.phantramSpinEdit.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForphantram)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.giamgiaBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            this.dataLayoutControl1.Controls.Add(this.phantramSpinEdit);
            this.dataLayoutControl1.DataSource = this.giamgiaBindingSource;
            this.dataLayoutControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayoutControl1.Location = new System.Drawing.Point(0, 0);
            this.dataLayoutControl1.Name = "dataLayoutControl1";
            this.dataLayoutControl1.Root = this.Root;
            this.dataLayoutControl1.Size = new System.Drawing.Size(253, 55);
            this.dataLayoutControl1.TabIndex = 0;
            this.dataLayoutControl1.Text = "dataLayoutControl1";
            // 
            // Root
            // 
            this.Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.Root.GroupBordersVisible = false;
            this.Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.layoutControlGroup1,
            this.ItemForphantram});
            this.Root.Name = "Root";
            this.Root.Size = new System.Drawing.Size(253, 55);
            this.Root.TextVisible = false;
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.AllowDrawBackground = false;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Location = new System.Drawing.Point(0, 0);
            this.layoutControlGroup1.Name = "autoGeneratedGroup0";
            this.layoutControlGroup1.Size = new System.Drawing.Size(233, 11);
            // 
            // phantramSpinEdit
            // 
            this.phantramSpinEdit.DataBindings.Add(new System.Windows.Forms.Binding("EditValue", this.giamgiaBindingSource, "phantram", true));
            this.phantramSpinEdit.EditValue = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.phantramSpinEdit.Location = new System.Drawing.Point(12, 23);
            this.phantramSpinEdit.Name = "phantramSpinEdit";
            this.phantramSpinEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
            this.phantramSpinEdit.Properties.Appearance.Options.UseTextOptions = true;
            this.phantramSpinEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            this.phantramSpinEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.phantramSpinEdit.Properties.EditValueChangedFiringMode = DevExpress.XtraEditors.Controls.EditValueChangedFiringMode.Default;
            this.phantramSpinEdit.Properties.Mask.EditMask = "P";
            this.phantramSpinEdit.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.phantramSpinEdit.Size = new System.Drawing.Size(229, 20);
            this.phantramSpinEdit.StyleController = this.dataLayoutControl1;
            this.phantramSpinEdit.TabIndex = 4;
            // 
            // ItemForphantram
            // 
            this.ItemForphantram.AllowHide = false;
            this.ItemForphantram.Control = this.phantramSpinEdit;
            this.ItemForphantram.Location = new System.Drawing.Point(0, 11);
            this.ItemForphantram.Name = "ItemForphantram";
            this.ItemForphantram.Size = new System.Drawing.Size(233, 24);
            this.ItemForphantram.Text = "%";
            this.ItemForphantram.TextSize = new System.Drawing.Size(0, 0);
            this.ItemForphantram.TextVisible = false;
            // 
            // giamgiaBindingSource
            // 
            this.giamgiaBindingSource.DataSource = typeof(DAL.giamgia);
            // 
            // f_giamgia
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(253, 55);
            this.Controls.Add(this.dataLayoutControl1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.Name = "f_giamgia";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Giảm giá/ Khuyến mãi";
            this.Load += new System.EventHandler(this.f_giamgia_Load);
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.f_giamgia_KeyDown);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayoutControl1)).EndInit();
            this.dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.Root)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.phantramSpinEdit.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForphantram)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.giamgiaBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private System.Windows.Forms.BindingSource giamgiaBindingSource;
        private DevExpress.XtraEditors.SpinEdit phantramSpinEdit;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraLayout.LayoutControlItem ItemForphantram;
    }
}